name: Copy _site folder to gh-pages

on:
  push:
    branches:
      - master
      - main

jobs:
  copy:
    name: Copy my _site folder to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC_FOLDER_PATH: '_site'
          TARGET_BRANCH: 'gh-pages'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          rm -rf *                          # remove all files
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          mv _site/* .                     # move the files to the root
          rm _site -r                      # remove the _site folder
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch